### ISSUE TITLE
CVV and expiration date

### ISSUE THREAD

**Issue by jmordkoff** [AuthorizeNet/sample-code-python#28]
This code accepts an invalid expiration date, even when I switch over to live mode.

This code does not show how to supply/validate the card holders name or the CVV. Is that possible?

**Comment by adavidw** [comment]
Hi @jmordkoff,

I added examples of things like CVV and name to the [authorize](https://github.com/AuthorizeNet/sample-code-python/blob/master/PaymentTransactions/authorize-credit-card.py) and [charge](https://github.com/AuthorizeNet/sample-code-python/blob/master/PaymentTransactions/charge-credit-card.py) samples in PR
https://github.com/AuthorizeNet/sample-code-python/pull/30.

Can you be more specific with what you mean with the expiration date, though?

**Comment by jmordkoff** [comment]
Hi @adavidw,

That turned out to be a server side config option that we had not set up right. Sorry I forgot to come back here and clarify.
