### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by danielgregorywilson** [AuthorizeNet/sample-code-python#35]
Running the individual samples from the readme fails, with no response returned. This matches what I am seeing in my own transaction unit tests. This seems to coincide with the TLS 1.2 update to the Sandbox environment.

I am working on a Django 1.7.7 project, with Python 2.7.10 and OpenSSL 1.0.2l (latest). This all matches what I am seeing here: https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Request-for-Comments-API-Best-Practices/ba-p/53668?utm_campaign=Merchant%20TLS%20Notice.html&utm_medium=email&utm_source=Eloqua

Is this my environment, or the library code? Is there anything else I need to do re: the upgrade?
https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/TLS-1-1-and-1-0-Disabled-in-Sandbox-on-April-30-2017-Updated/ba-p/57726

**Comment by adavidw** [comment]
Sorry, but it's almost certainly your environment. Try this at the command line:

`python -c "import json, urllib2; print json.load(urllib2.urlopen('https://www.howsmyssl.com/a/check'))['tls_version']"`
(that's all one line by the way)

That will connect to a test server which reports back to you what TLS version you're connecting as. If that doesn't say TLS 1.2, problems definitely your environment. If it does say TLS 1.2, the question would be why python from the command line could connect to some server correctly, but running our samples from the command line couldn't.
Please let us know what that test returns, and we'll go from there.

**Comment by danielgregorywilson** [comment]
Figured it out. I was using a 2015 version of python virtualenv, which was causing issues with SSL/TLS. Upgrading to current fixed all the tests. Thanks for your help!
