### ISSUE TITLE
No get-customer-payment-profile-list.py

### ISSUE THREAD

**Issue by kbuilds** [AuthorizeNet/sample-code-python#36]
Looks the the API reference expects a file, `get-customer-payment-profile-list.py` to be present in this repo, however this file is not present. This causes an error on the API reference site.

![image](https://user-images.githubusercontent.com/7346571/30947335-347db46c-a3d7-11e7-9cae-2dbb81f9fffa.png)

**Comment by adavidw** [comment]
Hi @kbuilds,

Thanks for bringing that to our attention. I've added a sample to the repository, so now the API Reference works, and correctly shows the sample in the site.

Turns out the node.js sample is missing as well, so looks like I'll be coding that one up also...

**Comment by kbuilds** [comment]
@adavidw Thanks for the quick turnaround. I should have just made the pull request myself as I already finished it. Sorry for not contributing back.

RE: node.js, I do not envy you :)
